plugin:
    name: 'icecollection.icenews::lang.plugin.name'
    description: 'icecollection.icenews::lang.plugin.description'
    author: icecollection
    icon: wn-icon-book
    replaces: {  }
navigation:
    main-menu-item:
        label: Новости
        url: icecollection/icenews/postcontroller
        icon: icon-stack-overflow
        sideMenu:
            side-menu-item:
                label: 'Управление тегами'
                url: icecollection/icenews/tagcontroller
                icon: icon-tags
            side-menu-item2:
                label: 'Управление категориями'
                url: icecollection/icenews/categorycontroller
                icon: icon-sitemap
            side-menu-item3:
                label: 'Список новостей'
                url: icecollection/icenews/postcontroller
                icon: icon-stack-overflow
            side-menu-item4:
                label: 'Добавить новость'
                url: icecollection/icenews/postcontroller/create
                icon: icon-keyboard-o
