# ===================================
# Filter Scope Definitions
# ===================================
scopes:

    category:

        # Filter name
        label: icecollection.news::lang.posts.category

        # Model Class name
        modelClass: IceCollection\News\Models\Category

        # Model attribute to display for the name
        nameFrom: name

        # Apply query scope
        scope: FilterCategories

    published:

        # Filter name
        label: icecollection.news::lang.posts.hide_published

        # Filter type
        type: checkbox

        # SQL Conditions
        conditions: published != true
