name: CategoryController
form: $/icecollection/icenews/models/category/fields.yaml
modelClass: icecollection\icenews\Models\Category
defaultRedirect: icecollection/icenews/categorycontroller
create:
    redirect: 'icecollection/icenews/categorycontroller/update/:id'
    redirectClose: icecollection/icenews/categorycontroller
update:
    redirect: icecollection/icenews/categorycontroller
    redirectClose: icecollection/icenews/categorycontroller
