list: $/icecollection/icenews/models/tag/columns.yaml
modelClass: icecollection\icenews\Models\Tag
title: TagController
noRecordsMessage: 'backend::lang.list.no_records'
showSetup: true
showCheckboxes: true
recordsPerPage: 20
toolbar:
    buttons: list_toolbar
    search:
        prompt: 'backend::lang.list.search_prompt'
recordUrl: 'icecollection/icenews/tagcontroller/update/:id'
