name: TagController
form: $/icecollection/icenews/models/tags/fields.yaml
modelClass: icecollection\icenews\Models\Tags
defaultRedirect: icecollection/icenews/tagcontroller
create:
    redirect: 'icecollection/icenews/tagcontroller/update/:id'
    redirectClose: icecollection/icenews/tagcontroller
update:
    redirect: icecollection/icenews/tagcontroller
    redirectClose: icecollection/icenews/tagcontroller
