name: PostController
form: $/icecollection/icenews/models/post/fields.yaml
modelClass: icecollection\icenews\Models\Post
defaultRedirect: icecollection/icenews/postcontroller
create:
    redirect: 'icecollection/icenews/postcontroller/update/:id'
    redirectClose: icecollection/icenews/postcontroller
update:
    redirect: icecollection/icenews/postcontroller
    redirectClose: icecollection/icenews/postcontroller
