list: $/icecollection/icenews/models/post/columns.yaml
modelClass: icecollection\icenews\Models\Post
title: PostController
noRecordsMessage: 'backend::lang.list.no_records'
showSetup: true
showCheckboxes: true
recordsPerPage: 20
toolbar:
    buttons: list_toolbar
    search:
        prompt: 'backend::lang.list.search_prompt'
recordUrl: 'icecollection/icenews/postcontroller/update/:id'
